name: Documentation

on: workflow_call

permissions:
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v3
      
      - name: Install dependencies
        run: |
          python -m pip install sphinx-toolbox
          pip install sphinx myst_parser
          sudo apt-get install doxygen graphviz -y

      - name: Sphinx build
        run: |
          pushd doc/sphinx
          sphinx-build ./ build
          popd

          echo "Sphinx was generated successfully!"

      - name: Store the generated doc
        uses: actions/upload-artifact@v4
        with:
          name: html-sphinx
          path: doc/sphinx/build
          
      - name: Doxygen build
        run: |
          pushd doc/doxygen
          mkdir -p build
          cd build
          cmake ../
          doxygen doxygen_doc/Doxyfile.doxy
          cd ..
          popd

          echo "Doxygen was generated successfully!"

      - name: Store the generated doc
        uses: actions/upload-artifact@v4
        with:
          name: html-doxygen
          path: doc/doxygen/build/html