name: Build projects
on:
  push:
    branches:
     - main
  pull_request:

  # enable manual triggering
  workflow_dispatch:
  
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update no-OS submodule
        run: |
          git submodule update --init libraries/no-OS

      - name: Run astyle on source code
        run: |
          sudo apt-get update
          sudo apt-get install -y astyle fd-find
          set -e
          formatted=$(fdfind -e c -e h . projects | xargs astyle --formatted --options=libraries/no-OS/ci/astyle_config)
          if [[ ! -z "${formatted}" ]]; then
            echo "ERROR: The following files were formatted by astyle:"
            echo "${formatted}"
            exit 1
          fi
          echo "SUCCESS: No files were formatted by astyle"

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        project:
          - ad405x_iio
          
    # Pull the container from the private repository
    container:
      image: ghcr.io/noahp/stm32wba55-example:2024-08-01
      #options: --user root
      #credentials:
       # username: ${{ secrets.ARTIFACT_USERNAME }}
        #password: ${{ secrets.ARTIFACT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build project
        run: |
          # Check contents of the root directory
          echo "Listing root directory:"
          ls -la /
          
          echo "Check pwd"
          pwd
          
          # Check contents of /opt directory
          echo "Listing /opt directory:"
          ls -la /opt
          
          /opt/st/stm32cubeide_1.16.0/stm32cubeide --launcher.suppressErrors -nosplash \
            -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
            -data /tmp/stm-workspace \
            -import "projects/ad405x_iio/STM32"

          /opt/st/stm32cubeide_1.16.0/stm32cubeide --launcher.suppressErrors -nosplash \
            -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
            -data /tmp/stm-workspace \
            -build ad405x_iio/Debug
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ad405x
          # The output artifacts are BLE_p2pServer.elf, BLE_p2pServer.map, etc.
          # Use a wildcard pattern to get them all
          path: projects/ad405x_iio/STM32/Debug/ad405x_iio.bin
          

