name: Deploy Doc 

on: workflow_call
jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'gh-pages'

    - name: Empty gh-pages
      run: |
        git rm -r . --quiet

    - uses: actions/download-artifact@v4
      with:
        name: html-sphinx
        
    - uses: actions/download-artifact@v4
      with:
        name: html-doxygen
        path: doxygen

    - name: Patch doc build
      run: |
        touch .nojekyll

    - name: Commit gh-pages
      run: |
        author=$(git log -1 --pretty=format:'%an')
        email=$(git log -1 --pretty=format:'%ae')
        commit=$(git rev-parse --short HEAD)

        git add . >> /dev/null
        git config --global user.name "$author"
        git config --global user.email "$email"
        git commit -m "deploy: $commit" --allow-empty


    - name: Push to gh-pages
      run: >-
        git push origin gh-pages:gh-pages
