on:
  push:
    branches:
      - workflow_imp

jobs:
  build-projects:
    uses: ./.github/workflows/build-projects.yml
    secrets: inherit
  check-versions:
    uses: ./.github/workflows/check-versions.yml
    needs: [build-projects]
    secrets: inherit
  lint:
    uses: ./.github/workflows/lint
    needs: [check-versions]
    secrets: inherit 
  documentation:
    uses: ./.github/workflows/documentation
    needs: [lint]
    secrets: inherit
  deploy-doc:
    uses: ./.github/workflows/deploy.yml
    needs: [documentation]
    secrets: inherit
